name = "netsuite-bi-ingest"
main = "src/worker.ts"
compatibility_date = "2024-08-22"
compatibility_flags = ["nodejs_compat"]

[vars]
PAGE_SIZE = "50"
MAX_PAGES_PER_RUN = "5"

[triggers]
crons = ["*/5 * * * *"]
